### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by s-m-e** [fusepy/fusepy#75] opened 2017-12-31 14:30 UTC
No offense, this is voluntary labor after all - I am just interest to know. In the issue tracker and pull requests, I see a lot of stuff happening, which has not been addressed or touched by the maintainer(s) for almost two years. Besides, folks point each other to the furthest progressed forks of this repository. However, as of writing this, non of the forks seems to have developed into a mature "replacement" project of its own (?).

As far as I can tell, ``fusepy`` is the best / most up-to-date / most feature-complete high-level FUSE-binding for Python. The status of its alternatives:

* [python-fuse](https://github.com/libfuse/python-fuse): Legacy Python only. As of February 2016 declared "orphaned" by the ``libfuse`` maintainer. 
* [python-llfuse](https://bitbucket.org/nikratio/python-llfuse/): Maintained, Python 3 support - but Low Level API only.

--- 

I [tested my way through ``fusepy``](https://github.com/pleiszenburg/loggedfs-python) with [pjdfstest](https://github.com/pjd/pjdfstest), which pointed me to a number of (potential) issues in ``fusepy``. I also experimented with ``fusepy`` and ``libfuse`` versions 3.x - long story short, at a first glance it appears there are a number of issues in ``fusepy`` prohibiting its use with ``libfuse`` 3. I do not mind reporting / bisecting / fixing (some of) them if there is an detectable interest in those issues or accepting pull requests.

**Comment by eestrada** [comment] 2017-12-31 19:27
I conversed with @terencehonles about this problem a year or two ago when I created a couple pull requests. At the time, he knew that he wasn't dedicating as much time as the project needed (due to work commitments), but that he didn't feel there was anyone else involved enough to safely hand it off to.

I think part of the issue is that there is only one admin of the repo. Ideally there should be at least two (so that one can choose to leave or go silent at any time without interrupting the project).

Perhaps, due to the lengthy communication lapse, it is time to hard fork (a la PIL to Pillow). In essence, keep everything in the same module namespace (so existing code using the module need not change), but run things as a separate project in an explicit github organization with multiple admins overseeing it so that it doesn't go dead again like this.

I think BDFL leadership is good because it gets things done quickly with a unified vision, but only if responsibility can transparently be handed off to someone else when the BDFL isn't available to fulfill all duties. That hasn't been happening in this case.

What are your thoughts @s-m-e? I'm happy to help admin if the hard fork is decided on, so long as I don't need to do it alone.

**Comment by s-m-e** [comment] 2018-01-01 00:13
Thanks @eestrada for your reply. I second most of your thoughts. What surprised my when I researched this topic - FUSE and Python bindings - was how scattered the attempts were and how little they were maintained. Other languages have well maintained go-to places (see Go and Node.js/JavaScript for instance) with a flourishing ecosystem of fairly advanced projects relying on those bindings. Python is surprisingly behind in this regard. In my opinion, FUSE bindings are a critical piece of infrastructure for modern "multi-purpose" programming languages. From my point of view it makes sense if the "stakeholders" aka the active users with projects relying on those bindings have a say in the bindings' maintenance. It reduces the number of competing approaches, bundles the available workforce and helps to establish a stable, well maintained project with lots of users.

I'd love to see how many people & projects actually rely on ``fusepy`` at this point and are willing to take it into this direction. 

As for me, I am considering to implement a somewhat more complex project in Python around a FUSE filesystem. For starters, I implemented a [pure Python drop-in replacement](https://github.com/pleiszenburg/loggedfs-python) of [LoggedFS](https://github.com/rflament/loggedfs) basically as an experiment and exercise. The original LoggedFS uses FUSE's higher level API (similar to ``fuse.py``). When I tested it with ``pjdfstest`` for POSIX compliance, I found only a few relatively [minor issues](https://github.com/rflament/loggedfs/issues/created_by/s-m-e). At least one of those issues is likely within ``libfuse`` 2.9 itself and may have been fixed in 3.x. So in theory, ``libfuse``'s high level API can support a POSIX compliant filesystem. However, when I look at my Python code, I see 25% of the tests failing while I can not attribute a lot of those failures to my code. This means ``fusepy`` is the likely source of my code's issues. Currently, I am considering to port my code to ``python-llfuse`` and see how that goes. But looking at the complexity of both types of bindings and the fact that installing ``python-llfuse`` requires code to be compiled, I'd prefer to base a larger, more serious project on a working ``fusepy`` package if those mentioned issues could be ironed out.

**Comment by pink-mist** [comment] 2018-01-03 10:45
> I'd love to see how many people & projects actually rely on fusepy at this point and are willing to take it into this direction.

I'm the downstream maintainer of the ```python-fusepy``` package for Slackware (on SlackBuilds.org), and at least on Slackware there was only one other project depending on python-fusepy, but it has been abandoned since the middle of 2017 for unrelated reasons. So currently I'm only keeping ```python-fusepy``` around since there hasn't been any solid reason to remove it.

**Comment by eestrada** [comment] 2018-01-04 05:18
@pink-mist Out of curiosity, what is the other project that depends on `python-fusepy`?

@s-m-e Before considering a hard fork too seriously I should restart the dialogue with @terencehonles directly and see if he is willing to hand off the project to me to maintain. He sounded close to handing it off to me before when we were communicating directly via email. This would be the best way to avoid disruption to downstream consumers packaging and using the code (such as @pink-mist). I'll update this thread once I have talked to @terencehonles again and got some updates.

I also just realized that, [looking at the contributors page](https://github.com/terencehonles/fusepy/graphs/contributors), I am currently the second most active contributor (after @terencehonles) that GitHub recognizes (although this doesn't take into account commits done previously by users that GitHub doesn't recognize). By that criteria, I can probably convince him that, as the second highest contributor after himself, I have some proof showing I care enough to help share the maintenance responsibilities.

**Comment by s-m-e** [comment] 2018-01-04 09:08
Please go ahead, @eestrada :) I have little interest in maintaining a fork of / on my own. I'd suggest to move the project into a neutral name-space and keep @terencehonles on - he has done excellent work. 

I dived deeper into the code of fusepy. The issues in my code that I mentioned earlier can mainly be attributed to quirks in the Python standard library, missing or wrongly specified FUSE options in general (fusepy does not automatically apply some FUSE "default" options) and some actual misconceptions on my part. I came down to 3% of the test suite failing at this point. The main remaining issue with fusepy prohibiting POSIX compliance is the way it handles times / timestamps. It was mentioned in issue #70, among other places: fusepy expresses seconds and fractions of seconds as floats. When the CPython interpreter was extended to handle timestamps with nanosecond resolution back in 2011, it was already found that [this was a bad idea](https://bugs.python.org/issue11457). I forked fusepy and implemented [this "fix"](https://github.com/terencehonles/fusepy/compare/master...s-m-e:master#diff-1d782d08fb7c4569538882342ebbc21c) to the problem, but it breaks backwards compatibility. I'll try the ``Decimal`` type instead, which should allow almost full backwards compatibility. If it works, I'll submit a patch.

Thanks to @pink-mist I had an idea: ArchLinux for instance maintains [lists of packages depending on another package](https://aur.archlinux.org/packages/python-fusepy/). For fusepy, they list the following projects: 

   * [acd_cli](https://github.com/yadayada/acd_cli)
   * [buildstream](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/_fuse/fuse.py) (maintains its own fork of fusepy within its codebase)
   * [envlinkfs](https://github.com/Akaricchi/envlinkfs)
   * [gitfs](https://github.com/PressLabs/gitfs)
   * [mpy-utils](https://github.com/nickzoic/mpy-utils)
   * [ytfs](https://github.com/rasguanabana/ytfs)

They're all maintained.

**Comment by pink-mist** [comment] 2018-01-04 10:15
It was acd_cli, and it is definitely not maintained, it is also no longer working for anyone but people who managed to get a security profile from amazon before they stopped offering those.

**Comment by s-m-e** [comment] 2018-01-04 10:20
Last commit in May 2017 ... looked (more or less) maintained to me. Sorry, my mistake.

**Comment by eestrada** [comment] 2018-01-04 17:01
@s-m-e as per your suggestion of a neutral namespace, I have created a [`fusepy` Github organization](https://github.com/fusepy) and invited @terencehonles to be a member of the organization. If/when @terencehonles transfers the repo there, [everything should just continue to work](https://help.github.com/articles/about-repository-transfers/); all of the issues/pull requests/wiki pages/releases/etc. will transfer with it. It will also make it so that anyone who points to https://github.com/terencehonles/fusepy will be redirected to the transferred repo within the organization.

**Comment by s-m-e** [comment] 2018-01-07 12:41
> I forked fusepy and implemented this "fix" to the problem, but it breaks backwards compatibility. I'll try the Decimal type instead, which should allow almost full backwards compatibility. If it works, I'll submit a patch.

I found a backwards compatible way of fixing the issue - see pull request #76. ``Decimal`` does not allow a fully transparent backwards compatible solution. It also requires conversions to and from strings, which I guess has quite an impact on a filesystem's performance. I ended up going down another path involving module attributes for switching behavior modes. 

With this patch, the ``fusepy`` high-level API is POSIX compatible. Which leaves the "issue" of porting it to ``libfuse3`` :)

@terencehonles and @eestrada: Have you guys had a chance to figure out how to go forward in the meantime?

**Comment by eestrada** [comment] 2018-01-09 01:52
@s-m-e I have reached out to @terencehonles, but he hasn't gotten back to me yet. I am going to try another email address for him that I didn't realize that I had before. Hopefully I can successfully reach him that way. By next week or the week after, if he doesn't reply to me, I will hard fork the repo and post the repo address here.

I looked at your pull request. It maintains backwards compatibility which is good. Also, avoiding `Decimal` is probably good too. I'll add a few comments directly on the pull request for minor things to change.

**Comment by eestrada** [comment] 2018-01-12 21:25
@s-m-e The other email address for @terencehonles did not produce any results either. I have just attempted to connect with him on LinkedIn to see if he will respond that way. My invite message mentions this project and the need for handing off maintenance. I'm starting to run out of ways to contact him.

**Comment by terencehonles** [comment] 2018-01-15 19:44
Hi guys, sorry about the delay. This time of year is a harder than normal time to get a hold of people so I apologize for the lack of response via email (I also don't really use LinkedIn anymore so that's not really any better than email)

I agree with needing a new set of maintainers for the project and @eestrada definitely seems willing to do the job (and has over time).

My main concern is down stream dependencies that may not realize the committers to the project are changing. Obviously this is the case with any open source project/library.

There are a couple things that I want to do:
1. Make it obvious for at least 6mo-1 year that there are new maintainers on the README
2. my repo @ /terencehonles will point to that commit (1 year - indefinitely(?)) and any work I do to contribute to the project I can do on a branch which can be merged into the org repo
3. bump the major version number (new maintainers + potentially breaking changes)

That is the critical list of things I want to do, but I haven't had much more time to think about this than the time to write this message (~10min). I know there were previously some concerns about how some things were implemented and I think if we bump to a new major version we can more freely look at and address the changes.

Unfortunately my time has been pulled away from fuse related projects and I don't have different machines to test other people's patches for different architectures so I am definitely at a loss. It would be nice if we could use an emulator to test some of this stuff, but pulling in more maintainers that actually use the systems will help in the long run.

**Comment by eestrada** [comment] 2018-01-15 20:09
@terencehonles regarding point 2, I think if we transfer the repo to an organization, you won't have a fork under `/terencehonles` anymore. That is because [anything pointing to your previous `fusepy` repo will automatically redirect to the new repo location](https://help.github.com/articles/about-repository-transfers/) (which I assume will be `/fusepy/fusepy`). For point 2, we can instead mention directly in the README the switch from living under `/terencehonles` to now living under `/fusepy`. I think that should be enough.

For point 3, I worry it will be confusing to bump the major version number when only changing the README. However, it makes a lot of sense to me to bump the major version number as soon as any code (such as @s-m-e's nanosecond PR #76) gets merged. However, that being said, I ultimately defer to your judgement on this.

**Comment by terencehonles** [comment] 2018-01-18 05:46
The project has been moved into the fusepy organization (where we are now). If anyone would like to join @eestrada in maintaining the project please speak up. If there are any PRs that @eestrada thinks should be merged I'll let him do so.

We'll work on sharing the publishing credentials so updates can be pushed to pypi

**Comment by s-m-e** [comment] 2018-01-18 06:59
@terencehonles & @eestrada This is great news. Thanks for making it happen. I am in. This package needs libfuse3 support. 

(I'll also redo #76. I just learned and fully understood the concept of how UTIME_OMIT is handled in libfuse, so my patch needs some rethinking I suppose.)

**Comment by mrocklin** [comment] 2018-01-18 16:51
Thank you all for taking this on.  I've been watching this thread and am
happy to see the outcome.

**Comment by s-m-e** [comment] 2018-01-18 19:14
@eestrada @terencehonles I'd like to suggest to have a chat / meeting of some sorts and give some proper thought to potential next steps, if you agree. The following points come to mind:

* Analysis of open pull requests and issues
* Python 2 and/or 3 support? 2017 saw a long awaited trend towards moving to Python 3 as the default in Linux distributions. At the same time, many significant packages have begun to drop Python 2 support. 
* Windows support (as has been developed in different flavors in some forks). It's an amazing feature to have.
* CI testing. Travis offers Linux and OS X (but lacks *BSD). Different architectures can be covered with Qemu (assuming speed does not matter while testing).
* Support for libfuse version 3 (and, at the same time, version 2?). At least in the Linux space, very few distributions adopted version 3 (or offer packages), so version 2 will remain relevant for the foreseeable future. On the other hand, version 2 has not seen development other than bug fixes for 2 years.
* Notifying downstream projects about the changed project status
* Asking downstream projects maintaining their own forks of fusepy about their interest / potential motivation in merging their changes and patches back into "upstream" fusepy
* Contacting maintainers of forks of fusepy itself, exploring their interest in merging their developments back into "upstream"
* Moving the module's code into a [src folder](https://blog.ionelmc.ro/2014/05/25/python-packaging/), making it easier to maintain
* Breaking the files fuse.py and fusell.py into files (sub-modules) specific to operating systems and architectures and common files. (And for people loving single-file modules, if requested, adding a "compiler" script for producing a single-file distribution/release version.)

I'd also like to suggest at least another maintenance release, like 2.0.x, for fixing bugs in the current code base - while development of a new release might happen in its own separate branch. It'll take time. There is also the option of releasing a package with breaking API changes under a new name like "fusepy3". I'd really like to keep the API as stable as possible.

Terence, I found a PGP key connected to your email addresses: 0x3155B117F701DDC8 (dating back to 2010). Is this key still valid? Mine is 0xfd4d117b0cf399a9.

Ethan, I did not manage to find a PGP key connected to your email address.

**Comment by itdaniher** [comment] 2018-01-18 19:25
>  (And for people loving single-file modules, if requested, adding a "compiler" script for producing a single-file distribution/release version.)

requested! I inline fusepy along with [kungfuse](https://github.com/stovenator/kungfuse) to deploy a souped-up virtualenv with a bunch of shared object files on systems without a compiler. Kind of like [pex](https://github.com/pantsbuild/pex) with better native system file support. Having a single file that abstracts FUSE is super useful.

**Comment by eestrada** [comment] 2018-01-21 05:28
@terencehonles Thanks for getting everything moved over. I'll email you directly about the pypi credentials since that obviously isn't something that should be exposed openly.

@s-m-e I am happy to see your enthusiasm. I'm happy to see everyone's enthusiasm. In the spirit of keeping the conversation transparent, I'd prefer to keep a conversation of priorities in the issue tracker here on Github. However, I want to start that in a separate issue from this one. I plan to close this issue shortly, now that the repo is moved and commit access is shared with more than one person, the core problem brought up by this issue is more or less solved. I'll start a new issue to discuss the roadmap for fixes/features.

Using the Github issue tracker is slower than a live chat on Gitter or a video call, but it keeps a more permanent record in a place where people expect to find such things. It also slows the conversation a bit, which is good since there are a lot of ideas and it will take time to integrate everything in a organized, clean fashion. Slowing the conversation a bit also allows everyone some time to raise their voice. So long as the conversation never stalls, going a little slower isn't a bad.

**Comment by eestrada** [comment] 2018-01-23 05:09
@s-m-e I have a PGP key, but it isn't on any key servers currently. I only have it [on Keybase](https://keybase.io/eestrada).

**Comment by terencehonles** [comment] 2018-02-13 00:24
@s-m-e yes that key should still work.

If you want to crack out issues for your line items we can track them individually. I'm going to close this issue because I don't want it to become a kitchen sink.

**Closed by terencehonles** 2018-02-13 00:24 UTC
Labels: question
