### ISSUE TITLE
Unexpected write arguments when running printf 'test\nhello\nworld'

### ISSUE THREAD

**Issue by sh54** [fusepy/fusepy#20] opened 2013-07-09 21:55 UTC
If I try to do something like:
`printf 'test\nhello\nworld' > mount_point/some_file`
I get 3 writes:
- offset: 0, data: test\n
- offset: 0, data: test\nhello\n
- offset: 0, data: test\nhello\nworld

I was expecting 'test', 'hello', and 'world' to get sent separately and I was not expecting to see the entire string sent to the 3rd write.

If I do a `dtruss` on that `printf` to a file in my normal filesystem I get the writes that I expect showing up ('test' then 'hello' then 'world').

Not sure if it is a fusepy thing, a `memory.py` thing or a bad assumption on my part.

My setup: OSX 10.6 with osxfuse in bash running the example filesystem `memory.py`.

**Comment by eestrada** [comment] 2018-01-31 04:57
@sh54 Is this still an issue? Does the same issue happen when you use [kungfuse](https://github.com/stovenator/kungfuse)?

**Comment by terencehonles** [comment] 2018-02-12 01:29
This is what I get:

```
DEBUG:fuse.log-mixin:-> write /test ('test\n', 0, 1L)
DEBUG:fuse.log-mixin:<- write 5
DEBUG:fuse.log-mixin:-> getxattr /test (u'security.capability',)
DEBUG:fuse.log-mixin:<- getxattr ''
DEBUG:fuse.log-mixin:-> write /test ('hello\n', 5, 1L)
DEBUG:fuse.log-mixin:<- write 6
DEBUG:fuse.log-mixin:-> getxattr /test (u'security.capability',)
DEBUG:fuse.log-mixin:<- getxattr ''
DEBUG:fuse.log-mixin:-> write /test ('world', 11, 1L)
DEBUG:fuse.log-mixin:<- write 5
DEBUG:fuse.log-mixin:-> flush /test (1L,)
DEBUG:fuse.log-mixin:<- flush 0
DEBUG:fuse.log-mixin:-> release /test (1L,)
DEBUG:fuse.log-mixin:<- release 0
```

I'm assuming because things are line buffered?

Or are you saying it is writing

```
test
test
hello
test
hello
world
```

I'm going to close this as working as intended... If you want to change `printf`'s behavior try this (you may need to find the relevant command on a Mac):

` stdbuf -o 1M printf 'test\nhello\nworld' > test`

**Closed by terencehonles** 2018-02-12 01:29 UTC
